export const allProd = [
    {
        "productName": "hp 250 g8",
        "productPrice": 325000,
        "productInfo": "hp 250 g8 10th generation laptop",
        "productImage1": "/image/hp-250-g8-img1.jpeg",
        "productImage2": "/image/hp-250-g8-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "hp",
        "batteryInfo": "45watt li-on battery",
        "ram": "8gb",
        "rom": "1tbhdd",
        "windowVersion": "windows 10 pro",
        "color": "silver",
        "netWeight": "1.3kg",
        "inch": "15",
        "gamingGraphics": "2gb dedicated gaming graphics"
        ,

    },
    {
        "productName": "lenovo legion 5",
        "productPrice": 650000,
        "productInfo": "lenovo legion 5 15IMH05 10th generation laptop",
        "productImage1": "/image/lenovo-legion-5-img1.png",
        "productImage2": "/image/lenovo-legion-5-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "lenovo",
        "batteryInfo": "integrated 60Wh",
        "ram": "8gb",
        "rom": "512gb ssd",
        "windowVersion": "windows 10 home",
        "color": "black",
        "netWeight": "1.3kg",
        "inch": "15.6",
        "gamingGraphics": "NVIDIA GTX 4GB GDDR6"

    },
    {
        "productName": "mac book pro",
        "productPrice": 1395000,
        "productInfo": "apple mac book pro 16\" AMD Raedon Pro 5500M",
        "productImage1": "/image/mac-book-pro-img2.jpeg",
        "productImage2": "/image/mac-book-pro-img1.jpeg",
        "processorType": "intel",
        "processorName": "corei9",
        "brand": "Apple",
        "batteryInfo": "96W USB-C power adapter Up to 11 hours battery life",
        "ram": "16gb",
        "rom": "1tb ssd",
        "windowVersion": "mac os",
        "color": "space grey",
        "netWeight": "2kg",
        "inch": "14.09",
        "gamingGraphics": "AMD Radeon Pro 5500M graphics card With 4GB of GDDR6 VRAM"

    },
    {
        "productName": "acer predator helios",
        "productPrice": 810000,
        "productInfo": "acer predator helios 300",
        "productImage1": "/image/acer-predator-helios-img2.jpeg",
        "productImage2": "/image/acer-predator-helios-img1.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "Acer",
        "batteryInfo": "Average Battery Life (in hours) ?6 Hours",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowVersion": "windows 10",
        "color": "black",
        "netWeight": "2.5kg",
        "inch": "15.6",
        "gamingGraphics": "Dedicated NVIDIA GeForce RTX 3060 6GB"

    },
    {
        "productName": " DELL XPS 17",
        "productPrice": 1555000,
        "productInfo": "DELL XPS 17 9700 10th generation laptop",
        "productImage1": "/image/c1-laptop-img.jpeg",
        "productImage2": "/image/c1-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "core19",
        "brand": "DELL",
        "batteryInfo": "Primary Battery 6-Cell Battery, 97WHr (Integrated)",
        "ram": "32",
        "rom": "1tb ssd",
        "windowVersion": "windows 10 pro",
        "color": "silver",
        "netWeight": "2.51kg",
        "inch": "17.0",
        "gamingGraphics": "NVIDIA GeForce RTX 2060 6GB GDDR6 with Max-Q"

    },
    {
        "productName": "DELL G5 Gamming pc",
        "productPrice": 460000,
        "productInfo": "DELL G5 Gamming 10th generation laptop",
        "productImage1": "/image/c2-laptop-img1.jpeg",
        "productImage2": "/image/c2-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "core15",
        "brand": "DELL",
        "batteryInfo": "Li-polymer 15.2v 68Wh 4-cell battery",
        "ram": "8",
        "rom": "256 ssd",
        "windowVersion": "windows 10 pro",
        "color": "black",
        "netWeight": "2.8kg",
        "inch": "15.6",
        "gamingGraphics": "4gb ram NVIDIA GeForce GTX 1650Ti"

    },
    {
        "productName": "Asus X515JA",
        "productPrice": 214000,
        "productInfo": "Asus X515JA laptop",
        "productImage1": "/image/c3-laptop-img1.jpeg",
        "productImage2": "/image/c3-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "core13",
        "brand": "ASUS",
        "batteryInfo": "Lithium Battery Energy Content ?37 Watt Hours 2 ion cells",
        "ram": "4",
        "rom": "1tb ssd",
        "windowVersion": "windows 10",
        "color": "Transparent silver",
        "netWeight": "1.7kg",
        "inch": "15.6",
        "gamingGraphics": "intel graphics card"

    },
    {
        "productName": "DELL latitude 3310",
        "productPrice": 265000,
        "productInfo": "DELL latitude 3310 core i3 256GB SSD..",
        "productImage1": "/image/dell-latitude-img1.jpeg",
        "productImage2": "/image/dell-latitude-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei3",
        "brand": "dell",
        "batteryInfo": "Polymer 3c 42 Watts battery with 11.40 VDC voltage",
        "ram": "8gb",
        "rom": "256GB",
        "windowVersion": "windows 10 pro(64-bit)",
        "color": "black",
        "netWeight": "1.17kg",
        "inch": "13.3",
        "gamingGraphics": "intel UHD graphics 620"
        ,

    },
    {
        "productName": "Acer nitro 5",
        "productPrice": 770000,
        "productInfo": "9th generation intel core i7 -9750H gamming laptop with backlit keybord",
        "productImage1": "/image/acer-nitro-5-img1.jpeg",
        "productImage2": "/image/acer-nitro-5-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "acer",
        "batteryInfo": "4 cell 57.5 Wh Lithium-Ion battery",
        "ram": "16GB DDR4 2666MHz",
        "rom": "256gb ssd",
        "windowVersion": "windows 10 home",
        "color": "black",
        "netWeight": "3kg",
        "inch": "15.6",
        "gamingGraphics": "NVIDIA GeForce RTX 2060 6GB GDDR6"

    },
    {
        "productName": "Hp omen 16",
        "productPrice": 1250000,
        "productInfo": "Hp omen 16 (60H77EA)",
        "productImage1": "/image/hp-omen-img1.jpeg",
        "productImage2": "/image/hp-omen-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "hp",
        "batteryInfo": "6-cell 83Wh Li-ion polymer",
        "ram": "32gb",
        "rom": "1tb ssd",
        "windowVersion": "Windows 11 Home",
        "color": "black",
        "netWeight": "2kg",
        "inch": "16.1",
        "gamingGraphics": "NVIDIA GeForce RTX 3070 8GB GDDR6"

    },
    {
        "productName": "Asus ROG ZEPHYRUS G1",
        "productPrice": 2000000,
        "productInfo": "Asus ROG ZEPHYRUS G1 AMD RYZEN 9-5900H",
        "productImage1": "/image/Asus ROG-img1.jpeg",
        "productImage2": "/image/Asus ROG-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "Asus",
        "batteryInfo": "1 Lithium ion batterie with 20Volts",
        "ram": "40gb DDR4",
        "rom": "2TB ssd",
        "windowVersion": "windows 10",
        "color": "Off black",
        "netWeight": "2.60kg",
        "inch": "15.51",
        "gamingGraphics": "8GB NVIDIA GeForce RTX 3070"

    },
    {
        "productName": "Apple macbook air",
        "productPrice": 590000,
        "productInfo": "Apple macbook air laptop with M1 chip",
        "productImage1": "/image/c4-laptop-img1.jpeg",
        "productImage2": "/image/c4-laptop-img2.jpeg",
        "processorType": "Apple M1",
        "processorName": "corei5",
        "brand": "Apple",
        "batteryInfo": "30W USB Type-C Power Adapter",
        "ram": "8gb",
        "rom": "256 ssd",
        "windowVersion": "macOS Big Sur 11.0",
        "color": "space grey",
        "netWeight": "0.7kg",
        "inch": "13",
        "gamingGraphics": "2gb ram"

    },
    {
        "productName": "Razer blade Stealth",
        "productPrice": 682000,
        "productInfo": "Razer Blade Stealth 13 GAMING laptop",
        "productImage1": "/image/c5-laptop-img1.jpeg",
        "productImage2": "/image/c5-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "Razer",
        "batteryInfo": "53.1Wh battery with up to 10hours battery life",
        "ram": "16gb",
        "rom": "256gb ssd",
        "windowVersion": "windows 10",
        "color": "black",
        "netWeight": "2.9kg",
        "inch": "13.3",
        "gamingGraphics": "NVIDIA GeForce GTX MX150 graphics card."

    },
    {
        "productName": "Lenovo v15",
        "productPrice": 258000,
        "productInfo": "Lenovo v15 laptop",
        "productImage1": "/image/c6-laptop-img1.jpeg",
        "productImage2": "/image/c6-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei3",
        "brand": "Lenovo",
        "batteryInfo": "4 Lithium Ion Cells with up to 8hours",
        "ram": "26gb",
        "rom": "1tb hdd",
        "windowVersion": "windows 10",
        "color": "black",
        "netWeight": "1.1kg",
        "inch": "15.6",
        "gamingGraphics": "Intel HD Graphics 610"

    },
    {
        "productName": "Microsoft surface pro 6",
        "productPrice": 645000,
        "productInfo": "Microsoft surface pro 6 laptop",
        "productImage1": "/image/c7-laptop-img1.jpeg",
        "productImage2": "/image/c7-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "Microsoft",
        "batteryInfo": "up to 6hours",
        "ram": "16gb",
        "rom": "512 ssd",
        "windowVersion": "windows 10",
        "color": "platinum",
        "netWeight": "0.77kg",
        "inch": "12.3",
        "gamingGraphics": "Intel HD Graphics "

    },
    {
        "productName": "Hp 240 G8 ",
        "productPrice": 280000,
        "productInfo": "Hp 240 G8 laptop",
        "productImage1": "/image/c8-laptop-img1.jpeg",
        "productImage2": "/image/c8-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei3",
        "brand": "HP",
        "batteryInfo": "PowerAC adapter power45 W",
        "ram": "12gb",
        "rom": "1tb hdd",
        "windowVersion": "windows 10 pro",
        "color": "Black",
        "netWeight": "1.47kg",
        "inch": "12.8",
        "gamingGraphics": "Intel HD Graphics "

    },
    {
        "productName": "Asus gaming pc",
        "productPrice": 690000,
        "productInfo": "Asus ROG STRIX gaming laptop",
        "productImage1": "/image/c9-laptop-img1.jpeg",
        "productImage2": "/image/c9-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "Asus",
        "batteryInfo": "1 Lithium ion battery",
        "ram": "16gb",
        "rom": "1tb ssd",
        "windowVersion": "windows 10 home",
        "color": "Black",
        "netWeight": "1.47kg",
        "inch": "15.6",
        "gamingGraphics": "NVIDIA GeForce GTX 1050 4GB graphics. Dual-fan thermal design"

    },
    {
        "productName": "DELL ALIENWARE",
        "productPrice": 1100000,
        "productInfo": "DELL ALIENWARE M15 R3 9th generation laptop",
        "productImage1": "/image/c10-laptop-img.png",
        "productImage2": "/image/c10-laptop-img2.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "DELL",
        "batteryInfo": "1 Lithium ion battery",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowVersion": "windows 10 home",
        "color": "Black",
        "netWeight": "4.7kg",
        "inch": "15.6",
        "gamingGraphics": "NVIDIA GeForce RTX 2060 6GB graphics and 6-phase voltage regulation"

    },
    {
        "productName": "infinix INbook",
        "productPrice": 470000,
        "productInfo": "infinix INbook laptop",
        "productImage1": "/image/c11-laptop-img2.jpeg",
        "productImage2": "/image/c11-laptop-img1.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "INFINIX",
        "batteryInfo": " 55Wh battery Up to 13 Hours of Web Browsing",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowVersion": "windows 10 home",
        "color": "Grey",
        "netWeight": "1.4kg",
        "inch": "14",
        "gamingGraphics": "NVIDIA GeForce RTX 2060 6GB graphics and 6-phase voltage regulation"

    },
    {
        "productName": "Hp Pavilion 15",
        "productPrice": 495000,
        "productInfo": "Pavilion 15 CONVERTIBLE laptop",
        "productImage1": "/image/c12-laptop-img2.jpeg",
        "productImage2": "/image/c12-laptop-img1.jpeg",
        "processorType": "intel",
        "processorName": "corei7",
        "brand": "HP",
        "batteryInfo": "41.5Wh 3 cell Li-polymer battery",
        "ram": "8gb",
        "rom": "256gb ssd",
        "windowVersion": "windows 10 home",
        "color": "Black and silver",
        "netWeight": "1.32kg",
        "inch": "15.6",
        "gamingGraphics": "intel graphics"

    }
]